version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: Password+
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
